name: agattp
description: Anlix Gateway Alternative Text Transfer Protocol.
version: 0.0.6
repository: https://github.com/anlix-io/agattp/
homepage: https://github.com/anlix-io/agattp/

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  # https://pub.dev/packages/convert
  convert: ^3.1.0

  # https://pub.dev/packages/crypto
  crypto: ^3.0.0

  # https://pub.dev/packages/http
  http: ^1.2.0

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.7.2

  # https://pub.dev/packages/lints
  lints: ^3.0.0

  # https://pub.dev/packages/markdown
  markdown: ^7.2.1

  # https://pub.dev/packages/test
  test: ^1.25.2

  # https://pub.dev/packages/testainers
  testainers: ^0.1.1
