name: agattp
description: Anlix Gateway Alternative Text Transfer Protocol.
version: 0.0.1
repository: https://github.com/anlix-io/agattp/
#homepage:

environment:
  sdk: '>=2.19.0 <4.0.0'

# dependencies:

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.6.3

  # https://pub.dev/packages/lints
  lints: ^2.1.0

  # https://pub.dev/packages/markdown
  markdown: ^7.1.0

  # https://pub.dev/packages/test
  test: ^1.24.0

  # https://pub.dev/packages/testainers
  testainers: ^0.0.6
